version: '2'

services:
  node-app:
    container_name: fix-c
    build:
      context: .
      args:
        - NODE_ENV=testing
    command: npm run test
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo-c
    ports:
      - '27017:27017'
    restart: always
    command: mongod --quiet --logpath /dev/null # Prevents MongoDB from logging to stdout
