version: '3.8'

services:
  node-app:
    image: ahmedelasiri/fixflex
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s

  nginx:
    image: nginx
    container_name: nginx-c
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
