version: '3.8'

services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=testing
    command: npm run test
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo-c
    ports:
      - '27017:27017'
    restart: always
    command: mongod --quiet --logpath /dev/null # Prevents MongoDB from logging to stdout
