// export * from './notification.interface';
export * from './auth.interface';
export * from './chat.interface';
export * from './errorResponse.interface';
export * from './tasker.interface';
export * from './message.interface';
export * from './response.interface';
export * from './offer.interface';
export * from './pagination.interface';
export * from './routes.interface';
export * from './category.interface';
export * from './socket.interface';
export * from './task.interface';
export * from './tasker.interface';
export * from './user.interface';
export * from './coupon.interface';
