name: Build and push Docker image

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          REGISTRY: fixflex
          IMAGE_TAG: latest
        run: |
          docker compose -f docker-compose.yml -f docker-compose.prod.yml build 
          docker compose -f docker-compose.yml -f docker-compose.prod.yml push node-app
