name: Run tests

on:
  pull_request:
    branches:
      - main
      - stage
      - develop

  push:
    branches:
      - main
      - stage
      - develop

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.20.0]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: npm install
      - name: create test.env file
        run: |
          touch test.env
          echo ACCESS_TOKEN_KEY_EXPIRE_TIME=${{ secrets.ACCESS_TOKEN_KEY_EXPIRE_TIME }} >> test.env
          echo ACCESS_TOKEN_SECRET_KEY=${{ secrets.ACCESS_TOKEN_SECRET_KEY }} >> test.env
          echo API_KEY=${{ secrets.API_KEY }} >> test.env
          echo APP_ID=${{ secrets.APP_ID }} >> test.env
          echo BASE_URL=${{ secrets.BASE_URL }} >> test.env
          echo CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }} >> test.env
          echo CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }} >> test.env
          echo COMMISSION_RATE=${{ secrets.COMMISSION_RATE }} >> test.env
          echo DEVELOPER_EMAIL=${{ secrets.DEVELOPER_EMAIL }} >> test.env
          echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> test.env
          echo GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} >> test.env
          echo PAYMOB_API_KEY=${{ secrets.PAYMOB_API_KEY }} >> test.env
          echo PAYMOB_HMAC_SECRET=${{ secrets.PAYMOB_HMAC_SECRET }} >> test.env
          echo PAYMOB_INTEGRATION_ID=${{ secrets.PAYMOB_INTEGRATION_ID }} >> test.env
          echo PAYMOB_INTEGRATION_ID_WALLET=${{ secrets.PAYMOB_INTEGRATION_ID_WALLET }} >> test.env
          echo PAYMOB_PUBLIC_KEY=${{ secrets.PAYMOB_PUBLIC_KEY }} >> test.env
          echo PAYMOB_SECRET_KEY=${{ secrets.PAYMOB_SECRET_KEY }} >> test.env
          echo PORT=${{ secrets.PORT }} >> test.env
          echo REFRESH_TOKEN_KEY_EXPIRE_TIME=${{ secrets.REFRESH_TOKEN_KEY_EXPIRE_TIME }} >> test.env
          echo REFRESH_TOKEN_SECRET_KEY=${{ secrets.REFRESH_TOKEN_SECRET_KEY }} >> test.env
          echo SALT_ROUNDS=${{ secrets.SALT_ROUNDS }} >> test.env
          echo CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }} >> test.env
          echo SMTP_HOST=${{ secrets.SMTP_HOST }} >> test.env
          echo SMTP_NAME=${{ secrets.SMTP_NAME }} >> test.env
          echo SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }} >> test.env
          echo SMTP_PORT=${{ secrets.SMTP_PORT }} >> test.env
          echo SMTP_USERNAME=${{ secrets.SMTP_USERNAME }} >> test.env
          echo USER_AUTH_KEY=${{ secrets.USER_AUTH_KEY }} >> test.env
          echo defaultLocale=${{ secrets.defaultLocale }} >> test.env
          echo DB_URI=${{ secrets.DB_URI }} >> test.env

      - name: Run tests
        run: npm run test
